version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: 'rabbitmq_container'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - rabbitmq-data:/var/lib/rabbitmq/
        - rabbitmq-log:/var/log/rabbitmq/
    networks:
        - rabbitmq_network
      
  producer:
    depends_on:
      - "rabbitmq"
    ports:
      - "3000:3000"
    build:
      context: ./order-service
      target: dev
    volumes:
      - .:/src
    command: sh -c '/bin/wait-for-it.sh rabbitmq:5672 --timeout=30 -- node index.js'
    environment:
      NODE_ENV: production
      AMQP_URL: amqp://guest:guest@rabbitmq:5672
      PORT: 3000

    networks:
      - rabbitmq_network

  consumer:
    depends_on:
      - "rabbitmq"
    ports:
      - "3001:3001"
    build:
      context: ./shipping-service
      target: dev
    volumes:
      - .:/src
    command: sh -c '/bin/wait-for-it.sh rabbitmq:5672 --timeout=30 -- node index.js'
    environment:
      NODE_ENV: production
      AMQP_URL: amqp://guest:guest@rabbitmq:5672
      PORT: 3001
    networks:
      - rabbitmq_network

volumes:
    rabbitmq-data:
    rabbitmq-log:

networks:
  rabbitmq_network:
    driver: bridge