version: "3.9"

services:
  item-app:
    image: ghcr.io/maxzx3000/item-app:v1
    depends_on:
      - item-db
    ports:
      - 80:8080
    working_dir: /app

  item-db:
    image: mongo:3
    volumes:
      - app-db:/data/db

volumes:
  app-db: